;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        ace-jump-move
        backward-sexp
        beginning-of-buffer
        comment-or-uncomment-region
        crux-kill-line-backwards
        end-of-buffer
        goto-line
        hydra--negative-argument
        indent-for-tab-command
        kill-region
        move-text-down
        my/smarter-move-beginning-of-line
        operate-on-number-at-point
        phi-search
        phi-search-backward
        python-nav-forward-block
        sh-assignment
        smart-hungry-delete-backward-char
        smart-hungry-delete-forward-char
        sp-remove-active-pair-overlay
        string-inflection-all-cycle
        ))

(setq mc/cmds-to-run-once
      '(
        ace-jump-mode
        ace-window
        handle-switch-frame
        helm-M-x
        hydra-mc/body
        hydra-mc/mc/compare-chars
        hydra-mc/mc/edit-beginnings-of-lines
        hydra-mc/mc/edit-beginnings-of-lines-and-exit
        hydra-mc/mc/edit-ends-of-lines
        hydra-mc/mc/mark-all-below
        hydra-mc/mc/mark-all-like-this
        hydra-mc/mc/mark-next-like-this
        hydra-mc/mc/mark-next-sexps
        hydra-mc/mc/mark-previous-like-this
        hydra-mc/mc/mark-previous-sexps
        hydra-mc/mc/reverse-regions
        hydra-mc/mc/skip-to-next-like-this
        hydra-mc/mc/unmark-next-like-this
        hydra-mc/mc/unmark-previous-like-this
        hydra-mc/mc/vertical-align-with-space
        hydra-mc/nil
        move-text-up
        yas-next-field
        ))
